server:
  port: 8080
  bind_address: 0.0.0.0
  secret_key: "eab05bb33012e641175559e9e99e8239bdd448ff13423e1bd86bc3b17e74e067"
  method: GET

ui:
  themes:
    - simple

engines:
  - name: google
    engine: google
  - name: bing
    engine: bing
  - name: duckduckgo
    engine: duckduckgo

search:
  safe_search: 0
  autocomplete: ""

outgoing:
  request_timeout: 5.0
